version: '3.8'

services:
  postgres_db:
    image: postgres:17-alpine
    container_name: waifu_postgres
    environment:
      POSTGRES_USER: waifu_bot_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: waifu_bot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  waifu_bot:
    build: .
    container_name: telegram_waifu_bot
    depends_on:
      - postgres_db
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_USER: waifu_bot_user
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: waifu_bot_db
      DB_SSLMODE: disable
    restart: unless-stopped
    
volumes:
  postgres_data: